[package]
name = "certsort"
version = "0.1.0"
authors = ["Ondřej Hošek <ondra.hosek@gmail.com>"]
edition = "2018"

[dependencies]
base64 = { version = "0.21" }
clap = { version = "4.1", features = ["derive"] }
pem = { version = "2.0" }
x509-parser = { version = "0.15.0" }
